"""add_accent_color_to_project

Revision ID: a8f6db6cd72a
Revises: de555be5f714
Create Date: 2026-02-28 11:09:13.892856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8f6db6cd72a'
down_revision: Union[str, Sequence[str], None] = 'de555be5f714'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('accent_color', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'accent_color')
    # ### end Alembic commands ###
