"""add_content_field_to_project

Revision ID: de555be5f714
Revises: 3c0f50f09bb9
Create Date: 2026-02-28 11:07:05.132426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de555be5f714'
down_revision: Union[str, Sequence[str], None] = '3c0f50f09bb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('content', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'content')
    # ### end Alembic commands ###
